### ISSUE TITLE
Add support for Last-Modified header

### ISSUE THREAD

**Issue by dmitrizagidulin** [solid/specification#154]
If a resource is readable, the `Last-Modified` header should be returned.

(Originally opened by @csarven)
(Moved from https://github.com/linkeddata/gold/issues/64)

From RFC 7232:

> An origin server SHOULD send Last-Modified for any selected
>    representation for which a last modification date can be reasonably
>    and consistently determined, since its use in conditional requests
>    and evaluating cache freshness ([RFC7234]) results in a substantial
>    reduction of HTTP traffic on the Internet and can be a significant
>    factor in improving service scalability and reliability.
> https://tools.ietf.org/html/rfc7232#section-2.2.1

**Comment by csarven** [comment]
The current spec sets MUST for 7232 (and actually SHOULD for Last-Modified in there) for servers, and MAY for clients.

For 7234, server SHOULD, client MAY.

As it stands, there is no particular functionality that needs Last-Modified as MUST for server. It can however come from elsewhere and that would be orthogonal.

The Best Practices and Guidelines document can make suggestions.

**Comment by csarven** [comment]
Given the changes in the Solid Protocol involving the `Last-Modified` header field ( https://solidproject.org/ED/protocol , https://solidproject.org/TR/2024/protocol-20240512 ), this issue can be revisited to make the requirement explicit. A PR to resolve this issue is available at: https://github.com/solid/specification/pull/678.
