### ISSUE TITLE
Which permissions are required for deleting a resource?

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#197]
When deleting a resource R in a container C, do we require:
- Write permissions on R?
- Write permissions on C?
- Both?
- Something else?

**Comment by RubenVerborgh** [comment]
+1 from me

**Comment by michielbdejong** [comment]
Yeah, I guess both options make sense, but your argument for changing this makes sense. If you have write on R then you can already set it to zero bytes which is almost the same as deleting it. Since it reduces the required permissions, it will not break many clients. But this is a semver-major change, so I'll change the behaviour in NSS 6.

I hadn't added any tests for this in https://github.com/solid/web-access-control-tests yet, so I'll immediately create the tests to test the new behaviour.

**Comment by acoburn** [comment]
+1 on _not_ requiring `acl:Write` on the container in order to allow deletion of a contained resource (assuming the agent has `acl:Write` permission on the contained resource).

**Comment by justinwb** [comment]
Also a very strong +1 to not requiring `acl:Write` on the container to delete a contained resource R when the agent has acl:Write on R.

> By not requiring Write on container to delete a contained resource, agents are not granted more access than what they need. Granting an agent with Write on container allows them to alter the container description as well as potentially modify or delete other (but not necessarily all) resources in the container.

Agree with @csarven and echo these points 1000% 👆

**Comment by csarven** [comment]
Great! Updated based on most recent consensus: https://github.com/solid/specification/commit/4fd701fcd451bd7a24c5a930d940a56297788991

**Comment by timbl** [comment]
Here is a counter argument to keep the need for Write access to the container also.   We have at the moment an invariant property of the system is that **if I remove Write access to something it won't change**.  

I like that.  It's logical. For example, if I am reading a file which has no write (or append) access then I  can cache it on a much more serious basis.   If I don't give anyone write access to a folder, I can assume, like for a file, that it won't change. If you then delete one of its contents, then that breaks - I thought I had a valid copy of the list, and I don't.

One of the directions we have talked about was getting into immutable resources.  An immutable resource is one where is is not only unwritable now but will never be writable in the future.   That's a fairly short step. With immutable resources, we  can refer to them by their hash. They can be Merkle trees,  you can  stick them in IPFS and do lots of other things.  You can send them to the Internet Archive as a final version of this resource. 

Lots of things get optimizable when something can't change.  You don't need to lock access to it at all. 

Being able to tie these good things to the ACL only having Read access is something we would lose.

**Comment by timbl** [comment]
I see I am too late with this comment

**Comment by timbl** [comment]
So if I want to keep my say /usr/local/ folder to always just have the fixed three /usr/local/ lib /usr/local/src and /usr/local/bin then I have to bock write access to it  **and each of the container folders** ?   The suggested change means that I  can't preserve my folder structure without both remove Write access for   /usr/local/  AND ALSO  /usr/local/ *    which defeats the  point as you can't use the child folders.

**Comment by timbl** [comment]
"""Granting an agent with Write on container allows them to modify the container description, potentially modify or delete all contained resources, as well as delete the container.""" -- Not "as well as delete the container" as for that they need W on its parent to.

**Comment by timbl** [comment]
If you allow files to be deleted from a folder without write access to that folder then surely you have to allow them to be added too?

**Comment by csarven** [comment]
>if I remove Write access to something it won't change

While agents with Control can make that assumption, agents with Read-only should not. Essentially only storage controller/"owner" can rightfully assume some resources to be immutable in context of immutable authorization policies.

Wouldn't the *promise* of immutable resources by URI owners be better advertised declaratively with eg. HTTP Link rel=type http://www.w3.org/2006/gen/ont#FixedResource , or negotiated using the Memento protocol ( http://mementoweb.org/ns#Memento ) ?

>if I am reading a file which has no write (or append) access then I can cache it on a much more serious basis. If I don't give anyone write access to a folder, I can assume, like for a file, that it won't change. If you then delete one of its contents, then that breaks - I thought I had a valid copy of the list, and I don't.

Controller shouldn't assume a container to be immutable if at the same it is possible to give Write access to a contained resource. Information about the container can change as a side-effect of changing its member, and so we should be careful about how this is interpreted. For example, while the the containment listing may not change after modifying a contained resource, container's description may be updated to indicate last modified date/time of a contained resource or even the container itself. [*nix filesystem does it]

---

> The suggested change means that I can't preserve my folder structure without both remove Write access for /usr/local/ AND ALSO /usr/local/ * which defeats the point as you can't use the child folders.

Yes, must remove Write in this case. Consider the case where a contained resource has its own ACL and you have Write on that resource. The algorithm doesn't need to check your permissions on the container in order for you to modify the resource. So then requiring Write on container in order to delete a resource is something different. If the delete operation is significantly different than the modify operation, then having Write on a resource doesn't necessarily mean you are allowed to delete. Something like `acl:Delete` would be required to make the distinction.

---

>Not "as well as delete the container" as for that they need W on its parent to.

True. [I've mistakenly introduced that when I edited the comment.]

---

>If you allow files to be deleted from a folder without write access to that folder then surely you have to allow them to be added too?

No. Append or Write is required on container to create a new resource in that container to begin with.

---

The issue is about changing the frame of how delete operations work in context of ACL and inheritance. From that perspective, I don't object to requiring both Write on container and contained resource in order to delete the contained resource.

To be clear, Write on a resource only entails access privilege to *modify* it. Only by also having Write on the container of a resource can *delete* work.

---

Limiting delete by requiring more privilege is a double edged sword. Great to set higher privileges for destructive operations but it is not particularly a simple design or intuitive - especially when one should only be able to delete a particular contained resource.

**Comment by timbl** [comment]
Added a user story [Be able to write protect a directory structure](https://solidos.solid.community/public/Roadmap/Access%20Control%20Lists/ACL%20Tasks/state.ttl#Iss1600084135495) : As pod owner, Alice wants to make sure that a certain structure at the top is preserved, for example say  /usr/local Container with three and only three sub Containers, /usr/local/lib /usr/local/src and /usr/local/bin say.  She wants Bob to be able to add new Resources and Containers to each of the thee, but not to delete those three Containers, or add any sub-Containers to /usr/local .

**Comment by csarven** [comment]
So, like a sticky bit on the container allowing only root/pod owner (and/or possibly anyone with Control?) to control the top directory structure?

Would you be content with a solution where stickiness (ie. preserving top container structure) is explicitly set in an authorization policy? That is as opposed to checking the container of a resource for Write access for a delete operation.

**Comment by timbl** [comment]
No, not new functionality, just removing Control access for the /usr/local from everyone else.

**Comment by timbl** [comment]
This user story is met by the current system, but would be broken by this proposal.

**Comment by timbl** [comment]
I propose we settle this on "both".

**Comment by csarven** [comment]
:)

I propose that we revert the spec requirement on deleting resources ie. Write on container and Write on contained resource are both required to delete the contained resource. I now believe that this approach would make the design more consistent. Here it goes:

---

As per hierarchical containment, resources are linked and unlinked from containers based on requested operation. Here is what we have for write, append and delete operations:

Consensus on Write and Append operations from https://github.com/solid/specification/issues/126#issuecomment-569920473 and https://github.com/solid/specification/issues/118#issuecomment-569648485 :

>[A]dding a new resource to a container entails: i) create resource, ii) add containment statement about the created resource, iii) create parent or ancestor containers, and their containment statements as necessary.

Proposed definition of a delete operation from https://github.com/solid/specification/issues/165#issuecomment-698939123 :

>Removing a resource from a container entails: i) delete resource, ii) remove containment statement about the deleted resource, iii) delete associated resources.

Changes to container are made atomically as per write, append and delete operations. Either all steps are fulfilled or none of them are.

As for permissions, adding a statement to containment listing ie. creating a new resource in a container, requires Append or Write access on the container. Hierarchical containment entails that requests to create or delete resources are routed through the resource's container because the resource is under the path segment of the container. Put differently, agent needs privileges to link and unlink resources of a container ie. access privileges to assign and cancel URIs with a particular path.

Deletion of a resource is fundamentally a write operation on the container as per hierarchical containment. Aside: for systems that permit orphaned resources, the lifecycle of a resource can be managed independently with no requirement or dependence on a container.

---

`acl:Append` or `acl:Write` are required on `/foo/` to create `/foo/bar`. `PUT`, `PATCH`, `PATCH` are requests to modify `/foo/`. Essentially `PUT` and `PATCH` require `acl:Write` on `/foo/bar` (whether resource exists or not) because client is assigning a URI to a resource. Whereas in `POST`, server assigns a URI to a resource, so only `acl:Append` (or `acl:Write`) is required on `/foo/`. If that's fulfilled, server links to `/foo/bar` from `/foo/`.

`DELETE /foo/bar` is a write request to modify `/foo/` such that `/foo/bar` gets unlinked (removed) from `/foo/`, hence `acl:Write` is required on `/foo/` and `/foo/bar`.

---

Giving Write access to a container would allow an agent to modify statements other than the containment, however, it would not allow them to delete all contained resources. Write access on each contained resource is still required.

**Comment by acoburn** [comment]
If the specification requires Write permission on a container in order to delete a resource, it is still possible to support both models discussed in this issue.

For containers with one level of hierarchy and with only `:Append` permission, an agent would not be able to delete a contained resource. For example, with `:Append` permission on `/container/` and a `:default` rule granting `:Write` permission on the contained resources (e.g. `/container/resource`), an agent will be permitted to modify that resource, including changing it to contain no triples.

On the other hand -- assuming the same initial permission structure: a client app has `:Append` permission on `/container/` and `:Write` permission on newly created resources inside that container -- the app can also achieve the alternative model, allowing deletes on resources. To do this, an app needs only to create an intermediate container before creating the resource: `/container/_/`. Then, anything added to `_/` can be deleted. For instance, `/container/_/resource` can now be deleted, since it would inherit the `:Write` permission from the `:default` statement in `/container/`.

**Comment by justinwb** [comment]
> As pod owner, Alice wants to make sure that a certain structure at the top is preserved, for example say /usr/local Container with three and only three sub Containers, /usr/local/lib /usr/local/src and /usr/local/bin say. She wants Bob to be able to add new Resources and Containers to each of the thee, but not to delete those three Containers, or add any sub-Containers to /usr/local .

I believe this user story is satisfied by giving Bob `acl:append` access to /usr/local/lib, /usr/local/src, and /usr/local/bin (unless i'm misinterpreting).

> Giving Write access to a container would allow an agent to modify statements other than the containment, however, it would not allow them to delete all contained resources. Write access on each contained resource is still required.

It's important to keep in mind that the container resource does not exist solely to store containment information. All kinds of information can be stored in the container resource graph because it's useful and intuitive to do so. We want to avoid allowing over-permissioned users from being able to change that data, or containment information, if it wasn't the resource controller's 
intention to let them do so.

There is an incongruence in having the ability to only add new resources into a container via `acl:append` (which is very useful), and a subsequent inability to delete those specific resources I added if I need to.

Consider this use case:

1. Alice gives her contacts group append access to a container for /comments/, with each comment being a new discrete resource.
1. Bob is one of Alice's contacts, and creates /comments/comment1
1. Peter is one of Alice's contacts, and creates /comments/comment2
1. Bob realizes that his boss Samantha is one of Alice's contacts, and reads her comments. Samantha doesn't like her team members doing social media during work hours, and the comments are timestamped.
1. Bob is unable to delete his own comment because he doesn't have write access to the /comments/ container. He clears out his comment, but the timestamped entry remains.
1. Bob is upset, so he calls Alice who gives him write access to /comments/. Bob deletes his comment. He also decides that he doesn't really like Peter, and deletes Peter's comment too.

**Comment by csarven** [comment]
>We want to avoid allowing over-permissioned users from being able to change that data, or containment information, if it wasn't the resource controller's
intention to let them do so.

Servers reject requests to update containment information irrespective of agent's access privilege ( https://solid.github.io/specification/#write ):

>Servers MUST NOT allow HTTP POST, PUT and PATCH to update a container’s containment triples; if the server receives such a request, it MUST respond with a 409 status code.

It prohibits - intentional or accidental - unlinking of resources through containers. It is not possible to create orphan resources and contained resources can't be orphaned. Hierarchical containment persists.

Giving an agent Write on container for the purpose of allowing them to delete contained resources can be considered as over-permissioning only to the extend where it would consequently "allow an agent to modify statements other than the containment". I am generally standing by my original point on this but at the same time don't consider it to be significant.

---

>There is an incongruence in having the ability to only add new resources into a container via acl:append (which is very useful), and a subsequent inability to delete those specific resources I added if I need to.

but:

>>Giving Write access to a container [..] would not [alone] allow them to delete contained resources. Write access on each contained resource is still required.

---

* Bob originally having only append on `/comments/` is granted to create `/comments/comment1` (via `POST /comments/` and server assigning `/comments/comment1`). He will not be able to modify `/comments/comment1` without Append or Write on it. So, he can't remove information from his comment to begin with.

* Bob can only delete his comment if he has Write on `/comments/` and `/comments/comment1`.

* Bob having Write on `/comments/` does not grant him to delete `/comments/comment2`. Alice would also need to give Bob Write on `/comments/comment2`.

**Comment by csarven** [comment]
Having hierarchical containment loosely coupled with WAC entails that a contained resource is under the authority/control/URI space (so to speak) of its container. Hence, a request to unlink is triggered via the resource that's targeted, and then processed based on the permissions set on itself and its container.

Requiring delete on the container of a contained resource is also consistent with the way a request to delete a root container are handled ( https://solid.github.io/specification/#delete ):

>When a DELETE request targets storage’s root container or its associated ACL resource, the server MUST respond with the 405 status code.

The underlying rule to delete consists of determining target resource's container. If the resource is contained, privileges on its container are determined. If resource is not contained - as in the case of root container - the request is rejected. The base case.

**Comment by timbl** [comment]
I believe this user story is satisfied by giving Bob acl:append access to /usr/local/lib, /usr/local/src, and /usr/local/bin (unless i'm misinterpreting).

You are misinterpreting.

**Comment by timbl** [comment]
> There is an incongruence in having the ability to only add new resources into a container via acl:append (which is very useful), and a subsequent inability to delete those specific resources I added if I need to.

I disagree.  It's not a bug, it's a feature.   With append-only access we are creating not a read-write space but we are allowing the semantics of sending messages.  Sending a message is a an event which is at core is not retractable. (You can have all kinds of variety of system which allow actually allow different forms of complete or limited retraction, but basically sending a message adds it to the ever-growing log of things sent, and is not revocable.)   In message-based systems, you can send a new message revoking  the effect of the first message, but you can't un-send a message.   This is valuable.

**Comment by timbl** [comment]
When I give something only read access, I expect it not to change.
If I give read and append access, I expect it only to grow.  Whether it is a list of contained resources or a set of triples in a RDF document.

**Comment by timbl** [comment]
Core invariants of the system like that make it simpler.   They make it better foundation to build other systems on top of.  Developers will get used to using them, and hopefully will find the systems easier to learn and easier to remember.

**Comment by justinwb** [comment]
> You are misinterpreting. She wants to allow to them to do whatever they want creating and deleting things inside /usr/local/lib, but not delete /usr/local/lib

To be fair, that is not what your use case says. The only mention of delete is that she not be allowed to delete _those three containers_ (/usr/local/lib, /usr/local/src, /usr/local/bin). With the added clarification that she should be able to delete things, it changes the approach. The follow-up question being - _which things?_. Only things that she creates, or anything in those three containers?

**Comment by justinwb** [comment]
> When I give something only read access, I expect it not to change.
> If I give read and append access, I expect it only to grow. Whether it is a list of contained resources or a set of triples in a RDF document.

I agree that when you have append on a document - you should have confidence that it can only grow. When giving an agent append access to a container, there is also value in scenarios where agents can only add new resources to the container, but have the ability to manage the resources they added (example case - https://solid.github.io/authorization-panel/wac-ucr/#collection-readappendwrite)

**Comment by justinwb** [comment]
> Giving Write access to a container [..] would not [alone] allow them to delete contained resources. Write access on each contained resource is still required.

Sorry @csarven I missed that point in the thread earlier. This does add another dimension to it, but if there was not a specific acl set on the resource, I imagine that inherited write permissions from the container would apply and satisfy that requirement?

**Comment by csarven** [comment]
>if there was not a specific acl set on the resource, I imagine that inherited write permissions from the container would apply and satisfy that requirement?

Only the policies including `acl:default` from the effective ACL are applied. In the absence of `acl:default`, permission is denied.

**Comment by csarven** [comment]
From hierarchical containment and access controls, I believe it follows that agents with `acl:Control` access on a container have full permission of the resources under its path. The purpose of this is to prevent agents from losing control of a path. The root container (`pim:Storage`) MUST have an ACL document - required by the inheritance algorithm - *and* it MUST include a policy with `acl:Control` access privilege.

I suggest to clarify this in the spec.

**Comment by csarven** [comment]
There are use cases to allow creators of resources to have some sense of right to control the lifecycle of their own creations.

In the case with multiple agents having `acl:Write` access to a container as per `acl:default`, it allows any agent to modify or delete (especially if `acl:Write` access is given to the container) others' resources. There is a need to distinguish agents if only the creators of resources should control (alternatively only read-write) them.

I'd like to connect this with https://github.com/solid/specification/issues/66 , https://github.com/solid/specification/issues/153 (and issues therein). The commonality is that agents that assign a URI to a resource also control it - who controls can change over time. This also includes the storage - root container (like `pim:Storage`).

Hence, reconfirming the need to record the creator/owner with respect to access controls. Related: `http://www.w3.org/ns/auth/acl#owner`.

**Comment by michielbdejong** [comment]
+1 to revert, i.e. going back to requiring Write on both C and R.

**Comment by michielbdejong** [comment]
For the record,

> agents with `acl:Control` access on a container have full permission of the resources under its path

That would be a spec change because that's not how Solid work currently.

> record the creator/owner with respect to access controls

Also not currently the case, but of course it's something we could introduce in a future spec change.

**Comment by bblfish** [comment]
What does it mean to give write access to a container? Does that not mean the ability to delete the container? If so how would one give someone the ability to edit only certain resources inside the container? (e.g. the ones they created?) without also giving them rights to dele the container? If one gives write access to only a subset of resources in a container, what is to stop someone removing all content from one of them, which is nearly equivalent to a delete?  It seems there is a tension between use cases here, that may be resolved in any number of ways.

1. We may want to add a history of resources so that deleting a resource does not mean removing the history of it (perhaps only making it invisible to certain groups). That could solve Tim's use case: the container owner would continue seeing the `ldp:contains` relation to the resource (history), and be able from there to see each state of the resource by following links.
2. The owner of the container could in an ACL make it (somehow) impossible for anyone who does not have write access to the container to get write access to any other resource in it. If this is recognizable then we can also get Tim's requirements, while allowing other containers that permit edits to contained resources too.

In any case we can add use cases such as [Tim's above](https://github.com/solid/specification/issues/197#issuecomment-692006903) to the WAC use case document. (note: The link in the use case does not work for me)

**Comment by csarven** [comment]
So then moving forward with the change: to delete a contained resource, Write required on both the container and the contained resource. Consistent with the rest of the design.

---

Related changes to be moved separately (with no dependency on what's discussed in this issue):

1.

>> agents with `acl:Control` access on a container have full permission of the resources under its path

>That would be a spec change because that's not how Solid work currently.

Right that the proposed change would prescribe behaviour that wasn't previously but it will eliminate implementation variation. At the moment, one implementation may allow loss of control of a subpath while another wouldn't. Are there any implementations with the intention where an agent controlling a path would be prevented from ever controlling a subpath because the subpath is being controlled by another agent? Losing control seems counter intuitive and problematic to me.

2.

>>  record the creator/owner with respect to access controls

>Also not currently the case, but of course it's something we could introduce in a future spec change.

There are also use cases where servers may not want to record the creator and clients may not want their identity associated (or tracked) with the created resource. For the latter, the client needs to make that request explicit and the server may accept.

**Comment by csarven** [comment]
>what is to stop someone removing all content from one of them, which is nearly equivalent to a delete?

It may appear to be equivalent in some situations however they are significantly different:
* Content modification (even if wiped) does not affect the lifecycle of the resource or associated resources (like ACL).
* When a resource gets deleted, server also deletes associated resources (like ACL).
* Deleting a resource is normally a concern of URI persistence and associated policies.
* Reinstating a previously deleted resource with the originally assigned URI may not be possible.

Having Write on a resource is not destructive without also having Write on its container.

**Comment by csarven** [comment]
As long as the controllers/owners (`acl:owner`) of a storage (`pim:Storage` / root container) can be distinguished from other agents with Control access on the storage (or any part) and owners can maintain their Control access on the whole storage, then it can be possible to allow non-owners to give someone else Control access to a resource. While the Control access giver (other than owners) may lose their Control of a resource and path under, it doesn't interfere with owners maintaining their Control on storage.

As Control access on a resource would only allow read/write access to its ACL, event agents having Control access on `/foo/bar` will need to have Write access on `/foo/` in order to delete `/foo/bar`. It follows that path structure can be preserved.

**Comment by csarven** [comment]
Thanks for this issue and discussion. Closing this issue as consensus is deemed to be captured in WAC Editor's Draft: https://solid.github.io/web-access-control-spec/ . See #authorization-evaluation , #reading-writing-resources , #loss-of-control-mitigation , #access-mode-extensions . Please use https://github.com/solid/web-access-control-spec for future discussion.
