### ISSUE TITLE
Which permissions are required for PUT to create?

### ISSUE THREAD

**Issue by michielbdejong** [solid/specification#236]
We agree that PUT to create resource `r` in container `c` requires a `default` Write grant on `c`.

NSS and PSS additionally require an `accessTo` Append or Write grant on `c`. After all, you're adding a containment triple.

It seems that CSS requires the `default` Write grant on `c` for creating the resource, but it does not require any `accessTo` grant on `c` for appending the containment triple.

I think the current CSS behaviour is incorrect, but @csarven  and @RubenVerborgh can you confirm?

**Comment by RubenVerborgh** [comment]
> I think the current CSS behaviour is incorrect, but @csarven and @RubenVerborgh can you confirm?

It comes down to what the spec says; what is the current text?

**Comment by michielbdejong** [comment]
> We agree that PUT to create resource r in container c requires a default Write grant on c.

Actually, found out that CSS requires either a `default` Write grant *or* a `default` Append grant on `c`. Same for PATCH-to-create.

**Comment by csarven** [comment]
Edit: I'm working through available text/consensus... so take the following based on what I've gathered - which may not be what everyone necessarily agrees with or implemented, and certainly not necessarily what I think should happen.

---

This issue is related to issue https://github.com/solid/specification/issues/193 with some subtle differences.

https://github.com/solid/specification/issues/193#issuecomment-679012925 attempts to clarify the current understanding for the shape of an authorization policy in that it requires:

>`acl:accessTo` and/or `acl:default`

[1] When a container's ACL document includes only one policy with `acl:default` (without `acl:accessTo`), the `acl:modes` of that policy are only set for the contained resources. Since the container has its own ACL, it also means that it does not inherit permissions from its parent container. No permission would be granted on the container.

>We agree that PUT to create resource `r` in container `c` requires a `default` Write grant on `c`.

>NSS and PSS additionally require an `accessTo` Append or Write grant on `c`. After all, you're adding a containment triple.

Putting aside the case where `r` has its own ACL, sure, that's a valid way to create `r` with PUT.

>It seems that CSS requires the default Write grant on `c` for creating the resource, but it does not require any `accessTo` grant on `c` for appending the containment triple.

Going with "seems": I think the CSS should not allow `r` to be created in that case.

Let me expand on that with this:

From https://github.com/solid/specification/issues/14#issuecomment-683480525 (loosely based on WAC - hoping to generalise this but that's an aside for now), see the table on PUT. Here are the interesting/relevant bits:

>```
>PUT C/R
>```
>|C/|C/R|C/R exists|C/R doesn't exist|
>|-|-|-|-|
>|-|Write|200|403|
>|Append|-|403|403|
>|Write|-|200|201|
>|Append|Write|200|201|

>Create requires Append (or Write) on C/ and Write on C/R.

Note also:

>All C/'s (containers) apply an access mode that can be inherited by C/R. Access mode marked with - indicates no access mode is explicitly set on resource. To provide some clarity, the tables incorporate some scenarios where access privileges are (hypothetically) set on non-existing resource.

A contained resource is under the authority/control/URI space of its container. There needs to be some way to add to/create in container's space.

When an ACL document contains no policy with acl:default, Append or Write only on C/ and requesting PUT C/R to create will be rejected.

Note in the above table having only Append on C/ or only write on C/R do not grant access to create. (Contrast this with POST C/ having only Append on C/ and it gets accepted - also because server allocates the URI for C/R.)

I believe this is also consistent with [1].

So, to answer:
>Which permissions are required for PUT to create?

Two policies in container's ACL document:
accessTo C/
mode Append (or Write)

default C/
mode Write

OR

Single policy in container's ACL document:
accessTo C/
defaultTo C/
mode Write

OR

Single policy in container's ACL document:
accessTo C/
mode Append (or Write)

Single policy in contained resource's ACL document:
accessTo C/R
mode Write

**Comment by michielbdejong** [comment]
>  I think the CSS should not allow `r` to be created in that case.

Thanks for clarifying @csarven! That was also my understanding.

**Comment by joachimvh** [comment]
> When an ACL document contains no policy with acl:default, Append or Write only on C/ and requesting PUT C/R to create will be rejected.

Does this not conflict with how the row with `C: Write` and `C/R: -` has a 200/201 response?

Looking at this from an implementation point of view, the one issue with the suggested response codes here is that there are some rows that return 4xx in case the resource doesn't exist and 2xx in case the resource does exist. This means the server needs to check if a resource exists while doing the authorization, which is definitely possible, but does make it more expensive since for most other forbidden calls it is generally not necessary to access the resource itself (only the relevant acl resources).

**Comment by michielbdejong** [comment]
And one more note on my introductory statement
> We agree that PUT to create resource `r` in container `c` requires a `default` Write grant on `c`.

It seems that ESS allows PUT-to-create of `r` in existing container `c` with just an `accessTo` Write grant on `c` and no need for a `default` grant on `c`.

**Comment by csarven** [comment]
@joachimvh ,

>>When an ACL document contains no policy with acl:default, Append or Write only on C/ and requesting PUT C/R to create will be rejected.

Aside: above assumes there is at least acl:accessTo, otherwise it'd be an invalid policy.

>Does this not conflict with how the row with C: Write and C/R: - has a 200/201 response?

No, they're different. The row Write, -, 200, 201 has a policy with acl:default. Reminder:

>All C/'s (containers) apply an access mode that can be inherited by C/R. Access mode marked with - indicates no access mode is explicitly set on resource.

So, PUT C/R in that row can be created. Whereas in the case without default ie. only Write on C/, then C/ can be replaced.

>Looking at this from an implementation point of view [..]

Let's work through specific rows to fix any errors. I can clarify the comment if you like but the whole point of the tables wasn't to couple authorization with response codes. Access checker will only give allow/deny. Servers use that information along with whatever else it wants to take into account to come up with the most appropriate status code. The tables came to be because the discussion was about which error codes to use.. and I wanted to clarify by laying it out based on the assumptions/principles.

**Comment by joachimvh** [comment]
> Let's work through specific rows to fix any errors. I can clarify the comment if you like but the whole point of the tables wasn't to couple authorization with response codes. Access checker will only give allow/deny. Servers use that information along with whatever else it wants to take into account to come up with the most appropriate status code. The tables came to be because the discussion was about which error codes to use.. and I wanted to clarify by laying it out based on the assumptions/principles.

Why I mentioned the difference between 4xx and 2xx is specific to the CSS implementation, but there the idea is that first all the authentication checks happen before sending the request to the actual resource. So if a request is forbidden the resource itself will never be accessed when processing that request. In case the permissions depend on the resource existing or not, the resource will have to be accessed to determine if it exists, which increases the complexity a bit there.

It also seems to be in line with previous discussions about servers leaking information about resources existing. In this case it's a very specific case of course, but it seems that if there are cases where the permissions differ based on a resource existing or not, this could give information away about this resource actually existing even if the agent requesting does not have permissions to know that.

**Comment by RubenVerborgh** [comment]
> the idea is that first all the authentication checks happen before sending the request to the actual resource

This is an important performance assumption in general BTW, which I think @acoburn might also share.

**Comment by acoburn** [comment]
Agreed. Worth noting that if permissions vary based on resource existence, a malicious agent could mount a timing attack to discover resource existence even if that agent has no access to the resource(s). E.g. if 4xx responses are, on average, 500ms slower in cases where resources exist, then an attacker can probe a server to discover information about a Pod without actually having access to those resources.

(There are mitigations to this where, for example, 4xx responses are held back and released only on second ticks (or any fixed period) -- that way, it is harder to distinguish between 100 and 900ms response errors)

**Comment by michielbdejong** [comment]
> It seems that ESS allows PUT-to-create of c/r in existing container c with just an accessTo Write grant on c and no need for a default grant on c.

Marking the need for a default Write as disputed as well. Will skip the related tests until we reach consensus.

**Comment by michielbdejong** [comment]
This thread touches on a number of topics, including difference between `acl:accessTo` and `acl:default`, performance considerations, code complexity considerations, security considerations, one reference to a bug, and if I count and hash them correctly, two references to disputes. I'll split out the two disputes in separate follow-up issues, so we can frame each of them as a boolean question.

**Comment by michielbdejong** [comment]
Actually the first dispute would basically be "what permissions do you need on `c/`", and since this is a newly created resource, we know that its ACL comes from `c/`'s default, so if we answer #193 with 'no' then that might also cover `c/`'s accessTo, and this question could become irrelevant. So to save discussion bandwidth, I'll wait until we settle #193 first, and then see if further clarification is still needed.

The second one is "what permissions do you need on `c/r`?" and while investigating that I got convinced that this is a bug in one of the implementations and not an actual spec dispute, so will report it as such elsewhere.

**Comment by michielbdejong** [comment]
No questions left about this now, other than #193 and #246.
