### ISSUE TITLE
Use inclusive language in Solid technical reports

### ISSUE THREAD

**Issue by csarven** [solid/specification#244]
Inspired by https://github.com/w3c/idcg/issues/17

**Comment by csarven** [comment]
Why would anyone need to be knowledgeable about science fiction? I think Guinan and Darmok are considerably better than Alice/Bob/Carl.. which happen to be very English-centric, and boring if I may add.

**Comment by RubenVerborgh** [comment]
I will just describe the effect it had on me: I don't know anything about science fiction, and when reading the specs, I came across names that I did not know or understand, and they felt they are an in-joke or reference that I was not part of. So I Google them, and see that it is a Star Trek reference, which I did not get, so I felt alienated/excluded.

That said, I am okay with that feeling for myself, because I have other ways of feeling included within Solid. So no need to change it for me.

But to people with a different background than myself, the alienation coming from references to something outside of their frame of reference might have a stronger reaction.

> Alice/Bob/Carl.. which happen to be very English-centric

How about https://forebears.io/earth/forenames?

**Comment by jeff-zucker** [comment]
I agree with @RubenVerborgh on this one.   Insider jokes that give people the feeling "everyone gets this but me" are not inclusive.  Names that emphasize ethnic/cultural diversity seem more appropriate here.

**Comment by TallTed** [comment]
I don't care if the chosen names are boring, as the point is not the names nor the non-people at all, but the activities in which they are supposed to be participating.  The only reason for using names at all is to make the usage scenario easier to think about.

No matter what language(s) we choose, someone will feel alienation or disinclusion, because we can't use every language at once.  Given that the docs are in English, it seems to me to make some sense for the placeholding names to be English-centric, as names from any other language/ethnicity/culture will be jarring from the textual flow to some degree.

Maybe, since every group that works on Use Cases & Requirements (among other) docs will run into this sooner or later, we should consider pushing for a cross-WG/CG/IG/XG/*G Task Force to build such an inclusive name set that everyone can use going forward, instead of all of us reinventing this wheel on a regular basis?

**Comment by csarven** [comment]
Happy to celebrate people/names from underrepresented etnical/cultural backgrounds.

I disagree with the example of a techie white guy not getting in on minor fun while working at Google... Using Guinan as example was to celebrate a wise black women. Yes, a scifi character. I picked one. The intention wasn't to exclude people but point taken if that offends some. We can improve. I created this issue and used those examples to change the frame .. hopefully for the better.

**Comment by csarven** [comment]
>No matter what language(s) we choose, someone will feel alienation or disinclusion, because we can't use every language at once.

That's not at all the point. Pick random names from different backgrounds.

>Given that the docs are in English, it seems to me to make some sense for the placeholding names to be English-centric, as names from any other language/ethnicity/culture will be jarring from the textual flow to some degree.

I could not disagree more. Completely missing the point.

**Comment by VirginiaBalseiro** [comment]
> But to people with a different background than myself, the alienation coming from references to something outside of their frame of reference might evoke a stronger reaction.

I personally have no knowledge of science fiction at all and I feel a much stronger reaction to "Bob" than a fictional character name.

**Comment by RubenVerborgh** [comment]
> I personally have no knowledge of science fiction at all and I feel a much stronger reaction to "Bob" than a fictional character name.

Would https://forebears.io/earth/forenames help? Or do yo know of other suggestions?

**Comment by TallTed** [comment]
My name is jarring in English- (and other-) speaking environments, when it's pronounced properly for its French origin, or when written in the Latin alphabet in a document that is primarily written in some other alphabet and/or language. C'est la vie.

Note that neither [Guinan](https://forebears.io/x/forenames/guinan) nor [Darmok](https://forebears.io/x/forenames/darmok) is used only by Star Trek characters; humans today use these, too, and they could well have resulted from the suggestion to "Pick random names from different backgrounds".

**Comment by VirginiaBalseiro** [comment]
> > I personally have no knowledge of science fiction at all and I feel a much stronger reaction to "Bob" than a fictional character name.
> 
> Would https://forebears.io/earth/forenames help? Or do you know of other suggestions?

Sure. But I don't see how fictional names get in the way of understanding the text in any significant way, to be honest. I don't feel one needs to be familiar with a name to understand that it is a name. But this is just my opinion.

**Comment by KyraAssaad** [comment]
I think we're at the risk of falling into the "I don't feel included by this, you don't feel included by that" rabbit hole and getting away from the topic at hand. 

I believe there is much to be said about using inclusive names in documentation and we should strive for that; Google has a nice guide on [inclusive documentation](https://developers.google.com/style/inclusive-documentation) and an example list of [inclusive names](https://developers.google.com/style/examples#example-person-names), as does [Splunk](https://docs.splunk.com/Documentation/StyleGuide/current/StyleGuide/Domains#Names). 

I (and [Google](https://developers.google.com/style/examples#further-notes-about-example-people)) agree that we shouldn't use [Alice and Bob](https://en.wikipedia.org/wiki/Alice_and_Bob).

As for using names from Star Trek, let's not forget that Star Trek pioneered [inclusion](https://www.supercluster.com/editorial/star-treks-most-significant-legacy-is-inclusiveness) and [diversity](https://www.huffpost.com/entry/lessons-from-star-treks-50-years-of-inclusion_b_57d18e70e4b0273330ac3852). 
> Roddenberry believed in an idea he termed as IDIC, or "infinite diversity in infinite combinations." The fundamental belief behind IDIC is a celebration of the diversity the universe has to offer. ([source](https://www.space.com/star-trek-diversity-inclusion-over-years.html))

Is Star Trek more popular and well-known in the West, and particularly in the US and Canada? Absolutely. Can specific pop culture references make people feel excluded? Certainly. But I would push back against not using the _names_ because they come from Star Trek, and instead suggest to pivot away from using Star Trek-specific scenarios that are deeper references to the series that people might not understand, be confused by or feel excluded by.

**Comment by langsamu** [comment]
I support inclusive language in technical reports and elsewhere, but I disagree that excluding either the RSA cast or the crew of the Enterprise makes writing more inclusive.

- We use forenames in technical writing to antropomorphise abstract concepts like 'user' and 'person'. If we standardise the name palette we risk losing the colloquial touch their usage brings.
- The freedom to bring style to your writing is itself an inclusive measure. "Whoever wrote this likes Star Trek. Ergo, this was written by an actual person." Not a commity, not a corporation.
- What makes documents inclusive and accessible is their technical content. Simple language, unambiguous phrasing, illustrative examples, examplary illustrations: These matter much more than choice of forenames.
- Alice and Bob are universally known standard actor denominations (in this universe of discourse). Who cares where they're from? We accept 'x' as a placeholder though other languages don't even use that character set.
- If I wrote something and chose Alíz and Boldizsár (Hungarian), that would look a bit awkward, but would it really make a difference? I think I should be free to do that, as long as I'm consistent and it doesn't hinder the text.
- If I wrote something else and chose אליס and בוב, that would really not look good in English technical writing. I wouldn't choose them. But I don't think I'd be excluding Hebrew speakers.



Here's my favourite quote from the W3C website:
> There is one particular misconception concerning the universal role restriction. As an example, consider the above happiness axiom. The intuitive reading suggests that in order to be happy, a person must have at least one happy child. Yet, this is not the case: any individual that is not a “starting point” of the property hasChild is a class member of any class defined by universal quantification over hasChild. Hence, by our above statement, every childless person would be qualified as happy.

-- https://www.w3.org/TR/owl2-primer/#Property_Restrictions

Why is OWL talking about family planning? Why the choice of the parent-child relationship? Is the audience all parents? Will everyone agree with the conclusion? Is this not insensitive?

I think language like the above makes writing better, because it's funny and it's human. It's relatable.

It's a joke.

**Comment by jeff-zucker** [comment]
> Alice and Bob are universally known standard actor denominations (in this universe of discourse). 

They are universally known because a bunch of men, mostly white and mostly Euro-American chose them and used them.   Sticking with things because "that's the way we've always done them" is exactly the way societies stay closed.  It's a strategy that supports the status quo and those who already have power.  

> Who cares where they're from? 

I do.  The Solid diversity, equity, and inclusion team does.  A number of people in this thread do.  As mentioned above the Google and Splunk documentation teams do.  You are quite free to say that the use of these names does not bother you.  If you want to jump from there to the assumption that they do not bother anyone else, that is quite a leap.

**Comment by elf-pavlik** [comment]
> https://developers.google.com/style/examples#example-person-names

This one looks like a short decent list which we could use as a reference

> https://forebears.io/earth/forenames

I find it a nice source but It might need a bit of filtering. For example, we could avoid religious figures like Maria, Jose, David, Mohammed. Not to discriminate, only to keep things secular.

I'm co-editing a handful of solid specs and primers. What I would find helpful would be a reference, similar to the one from Google. Which would also include links to pronunciation, eg. https://www.howtopronounce.com/izumi

Such a list of 30 selected, easy to pronounce by non-native English speakers, names to choose from would probably cover anything all the specs and primers would ever need.

While we are on it, I wish there would be also a list of fictional organizations. Currently, I'm using names like ACME, Omni, Yoyodyne but having a reference list with 5 - 10 fictional organizations would come in super handy.

**Comment by TallTed** [comment]
> Such a list of 30 selected, easy to pronounce by non-native English speakers, names to choose from would probably cover anything all the specs and primers would ever need.
> 
> While we are on it, I wish there would be also a list of fictional organizations. Currently, I'm using names like ACME, Omni, Yoyodyne but having a reference list with 5 - 10 fictional organizations would come in super handy.

It's somewhat astounding that IANA or the like hasn't done and published this sort of work already!

**Comment by KyraAssaad** [comment]
> While we are on it, I wish there would be also a list of fictional organizations.

I've used https://mockaroo.com/ in the past to create lists of fake data; they have a fake company name list which is pretty good.

**Comment by csarven** [comment]
https://github.com/w3c/idcg/issues/17#issuecomment-993679054

**Comment by justinwb** [comment]
> I'm co-editing a handful of solid specs and primers. What I would find helpful would be a reference, similar to the one from Google. Which would also include links to pronunciation, eg. https://www.howtopronounce.com/izumi

Agree - it would be fantastic if we had a place to pull from consistently. Would it be possible for the Solid DEI team to take this up as an initiative and publish guidance? That way if issues come up with names in the future they can be directed to that and the guidance can be amended as needed.

**Comment by jeff-zucker** [comment]
I'll mention this in our chatroom and bring it up at our next meeting. It does seem like a doable thing that the DEI group is the right group to do.

**Comment by csarven** [comment]
Also something fun/ironic about Darmok being a reference to a story about coming to shared understanding from vastly different perspectives.

**Comment by csarven** [comment]
Thanks all!

With https://github.com/solid/specification/commit/9cc97ed9de9f529aada3456c75169559ca3b0174 resolving this issue:

I've updated the [Contributing Guide](https://github.com/solid/specification/blob/main/CONTRIBUTING.md#self-review) with the feedback from this issue towards celebrating people/names from under represented ethnic/cultural backgrounds in examples, as well as GitHub's content style guide for using [inclusive language](https://github.com/github/docs/blob/main/contributing/content-style-guide.md#inclusive-language) (that includes references to other guides.)

Improvements/recommendations always welcome. See also https://github.com/w3c/idcg/issues/17 for additional developments/resources.
