### ISSUE TITLE
Alternative update support with N3 patch

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/specification#332]
## Context
The Solid protocol specifies a mechanism to update resources via HTTP `PATCH` (https://github.com/solid/specification/issues/85) whereby the contents of the change are expressed in the HTTP body.

## Description of current status and problems

The currently proposed media type for these updates is that of the [SPARQL 1.1 Update](https://www.w3.org/TR/sparql11-update/) specification. However, Solid servers deviate from this specification in important ways:
- Only a subset of the SPARQL 1.1 Update language is supported:
  - https://github.com/solid/specification/issues/125
  - https://github.com/solid/specification/pull/320
- There is a desire to have different matching semantics:
  - https://github.com/solid/specification/issues/322
  - https://github.com/solid/solid-spec/pull/193
  - https://github.com/solid-archive/query-panel/issues/3

A currently proposal suggests to use a different (but SPARQL-inspired) syntax altogether in order to avoid confusion with the actual SPARQL 1.1 Update language:
  - https://github.com/solid/specification/pull/330

Whereas I understand the reasoning behind that, I see a couple of problems:
- There are no existing server or client implementations
  - All servers would have to be changed
  - All clients would have to be changed
- The proposed syntax is non-standard
  - This is concerning from a Solid philosophy where we strive to use standards
  - It also means that implementations cannot reuse existing stacks, but have to roll their own

## Proposed solution
My proposal is an N3 patch format as a solution for the 0.9 release.

### Advantages
- Support has been implemented and tested in NSS since 2017
- RDFlib.js code exists for it
  - So JavaScript clients can be migrated easily with an RDFlib.js upgrade
- It is a largely standards-based approach
  - Off-the-shelf parsers already exist for multiple programming languages
- We are in control of the semantics
  - And the semantics are extensible because it is an RDF format

### Disadvantages
- N3 is not an actual W3C standard
- We still require changes to clients and servers

### Examples
A working example patch looks as follows (MIME type `text/n3`):

```turtle
@prefix solid: <http://www.w3.org/ns/solid/terms#>

<> solid:patches <https://tim.localhost:7777/read-write.ttl>;
   solid:where   { ?a <y> <z>. };
   solid:inserts { ?a <y> <z>. };
   solid:deletes { ?a <b> <c>. }.
```

Thee above terms are all defined in https://www.w3.org/ns/solid/terms.

More examples are available in the [tests](https://github.com/solid/node-solid-server/blob/main/test/integration/patch-test.js) I have written for NSS; they can also be tried live against any NSS >=4.x server.

**Comment by kjetilk** [comment]
I'm having conflicting feelings about this... Perhaps part of that conflicting feeling is just a sunk cost fallacy because I've put so much time into a SPARQL patch... 

On one hand, I'd wouldn't want to mangle SPARQL way out what it was designed for, and I feel that we were getting to a place where we shouldn't. Using SPARQL for a `PATCH` body is not a misappropriation, that is actually a use case of SPARQL. 

OTOH, I feel that what we could do to support the semaphore mechanism isn't *that* bad, if we could just examine what we really need. In particular, I don't feel I have a good answer to the question:

When needing the semaphore mechanism, is the triple that is being changed known to the client?

If the answer to that is "yes", or "I guess that's good enough", I think we can design a simple mechanism that is easy to implement with SPARQL that is also likely to find support in a future SPARQL WG. If the answer is a definitive "no", then much more extensive work is required to come up with something that would sit well in a future SPARQL WG.

Now, I still feel that we should have an answer to that question, because it should influence the design of an N3 patch too.
