### ISSUE TITLE
Will WebSocket support be part of the Solid specification

### ISSUE THREAD

**Issue by acoburn** [solid/specification#50]
The 0.8 Solid Spec defines an [API for WebSockets](https://github.com/solid/solid-spec/blob/master/api-websockets.md). Will that become part of the 1.0 Solid specification or is that feature at risk? A WebSocket API is not currently mentioned in the Solid Ecosystem document.

**Comment by RubenVerborgh** [comment]
We definitely need a mechanism for realtime, possibly through WebSockets.

However, what is sketched in the v0.8 draft is a quick hack with several known flaws. It was never engineered to last. We should not continue it.

The Ecosystem document has a section for update notifications, where this fits under. However, since this will be a client-server topic, its top heading probably needs renaming.

**Comment by RubenVerborgh** [comment]
Also, there has been a requirements engineering effort regarding realtime updates. It can be used as a basis for engineering a proper solution.

**Comment by kjetilk** [comment]
There is also an open question whether the realtime update requirements could be satisfied with HTTP/2, with server sent events ([I'm not a big fan](https://github.com/solid/solid-spec/issues/123)) or something like it. I think that should be a part of this discussion.

**Comment by elf-pavlik** [comment]
#122 discusses possibility of using http including option of using http streaming response body rather tahn server-sent events ([EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource))

**Comment by timbl** [comment]
Web socket support is already IN the solid ecosystem.   Has been for years, before NSS even.  I think ldnode and ldphp supported it IIRC.  Live update of displays by multiple clients is crucial to the collaborative editing apps, and to solid chat of course. 

It is currently being upgraded to include an authentication token to prevent it being eaves-dropped on.

Enhancements could include sending a patch back to the client, instead of just a flag that the document has changed.
Enhancements can be discussed in other issues. 

But the answer is "yes".
