### ISSUE TITLE
Update notifications protocol in TR overview

### ISSUE THREAD

**Issue by woutermont** [solid/specification#560]
The version of the Notifications Protocol the TR page links to is still one from December 2022. An update would be welcome, given how many progress there has been on that front.

**Comment by csarven** [comment]
Indeed there are some significant updates.. but this lands on notifications-protocol and on us to make the 0.3 release. Hint hint no pressure nudge cherry on top...

We wanted to wrap-up a few other significant-ish updates for 0.3.. in order to update the TR. There are a couple of issues/PRs to finalise.

Hoping you don't mind me closing this issue. Open to discuss further in chats...
